load("//third_party/bazel_rules/rules_python/python:py_test.bzl", "py_test")

package(
    default_applicable_licenses = ["//third_party/tf_opt:license"],
    default_visibility = [
        "//visibility:public",
    ],
)

licenses(["notice"])
