package(
    default_visibility = [
        "//visibility:public",
    ],
)

licenses(["notice"])

cc_library(
    name = "clif_tensor_test_functions",
    hdrs = ["clif_tensor_test_functions.h"],
    deps = [
        "//tf_opt/tensor",
        "//tf_opt/tensor:reduce",
        "@com_google_ortools//ortools/base",
    ],
)
